[package]
name = "fusor-types"
version = "0.1.0"
authors = ["Evan Almloff <evanalmloff@gmail.com>"]
license = "MIT/Apache-2.0"
edition = "2024"

[dependencies]
bytemuck = { version = "1.14", features = ["derive"] }
