[package]
name = "kalosm-vision"
version = "0.2.0"
edition = "2021"
description = "A set of pretrained vision models "
license = "MIT/Apache-2.0"
repository = "https://github.com/floneum/floneum"
authors = ["Evan Almloff"]

[dependencies]
image = "0.24.7"
kalosm-ocr.workspace = true
rwuerstchen.workspace = true
segment-anything-rs.workspace = true

[features]
metal = ["kalosm-ocr/accelerate", "rwuerstchen/accelerate", "segment-anything-rs/accelerate"]
cublas = ["kalosm-ocr/cuda", "rwuerstchen/cuda", "segment-anything-rs/cuda"]
