[package]
name = "kalosm-vision"
version = "0.4.0"
edition = "2021"
description = "A set of pretrained vision models "
license = "MIT/Apache-2.0"
repository = "https://github.com/floneum/floneum"
authors = ["Evan Almloff"]
keywords = ["ai", "segment-anything", "ocr"]

[dependencies]
image = "0.24.7"
kalosm-ocr.workspace = true
rwuerstchen.workspace = true
segment-anything-rs.workspace = true

[dev-dependencies]
kalosm = { workspace = true, features = ["vision"] }
futures-util = "0.3.28"
tokio = { version = "1", features = ["full"] }

[features]
metal = ["kalosm-ocr/metal", "rwuerstchen/metal", "segment-anything-rs/metal"]
cublas = ["kalosm-ocr/cuda", "rwuerstchen/cuda", "segment-anything-rs/cuda"]
mkl = ["kalosm-ocr/mkl", "rwuerstchen/mkl", "segment-anything-rs/mkl"]
