[package]
name = "kalosm-vision"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.7"
rwuerstchen.workspace = true
segment-anything-rs.workspace = true
