[package]
name = "rwuerstchen"
version = "0.3.2"
edition = "2021"
description = "A simple interface for RWuerstchen image generation models models"
license = "MIT/Apache-2.0"
repository = "https://github.com/floneum/floneum"
authors = ["Evan Almloff"]
keywords = ["ai", "rwuerstchen", "image-generation"]

[dependencies]
candle-core.workspace = true
candle-nn.workspace = true
candle-transformers.workspace = true
tokenizers.workspace = true
hf-hub = "0.3.0"

accelerate-src = { version = "0.3.2", optional = true }
intel-mkl-src = { version = "0.8.1", features = ["mkl-static-lp64-iomp"], optional = true }
cudarc = { version = "0.9.14", features = ["f16"], optional = true }
half = { version = "2.3.1", features = ["num-traits", "use-intrinsics", "rand_distr"], optional = true }
kalosm-common = { workspace = true }
kalosm-language-model.workspace = true
kalosm-streams.workspace = true

futures-util = "0.3.28"
image = "0.24.7"
tokio = { version = "1.32.0", features = ["full"] }
tracing = "0.1.37"

[dev-dependencies]
anyhow.workspace = true

[features]
flash = ["candle-transformers/flash-attn"]
accelerate = ["dep:accelerate-src", "candle-core/accelerate", "candle-nn/accelerate", "candle-transformers/accelerate"]
cuda = ["candle-core/cuda", "candle-nn/cuda", "candle-transformers/cuda"]
cudnn = ["candle-core/cudnn"]
mkl = ["dep:intel-mkl-src", "candle-core/mkl", "candle-nn/mkl", "candle-transformers/mkl"]
nccl = ["cuda", "cudarc/nccl", "dep:half"]
metal = ["candle-core/metal", "candle-nn/metal", "candle-transformers/metal", "kalosm-common/metal"]
