[build]
rustflags = ["-C", "target-cpu=native"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "target-feature=-avx,-avx2"]

# [unstable]
# build-std = ["std", "core", "alloc"]
# build-std-features = ["panic_immediate_abort"]
