[package]
name = "kalosm-language"
version = "0.4.1"
edition = "2021"
description = "A set of pretrained language models "
license = "MIT/Apache-2.0"
repository = "https://github.com/floneum/floneum"
authors = ["Evan Almloff <evanalmloff@gmail.com>"]
keywords = ["ai", "llm", "llama", "mistral", "nlp"]

[dependencies]
futures-util = "0.3.28"
rand = "0.8.5"
reqwest = { version = "0.11.18", features = ["stream", "json"] }
tokio = { version = "1.28.1", features = ["fs"] }
slab = { version = "0.4.8", features = ["serde"] }
arroy = "0.5.0"
heed = "0.20.0-alpha.9"
serde = { version = "1.0.163", features = ["derive"] }
url = "2.4.0"
tracing = "0.1.37"
serde_json = "1.0.107"
chrono = { version = "0.4.31", features = ["serde"] }
readability = { version = "0.2.0", default-features = false }
tempfile = "3.8.0"
rss = { version = "2.0.6", features = ["atom"] }
scraper = { version = "0.19.0", features = ["atomic"] }
kalosm-language-model = { workspace = true }
headless_chrome = { version = "1.0", optional = true }
tokio-util = { version = "0.7.9", features = ["rt"] }
dashmap = { version = "5.5.3", optional = true }
rbert = { workspace = true, optional = true }
kalosm-llama = { workspace = true, optional = true }
kalosm-streams.workspace = true
pulldown-cmark = "0.9.3"
docx-rs = "0.4.7"
lopdf = { version = "0.35.0", features = ["async"] }
convert_case = "0.6.0"
kalosm-sample = { workspace = true }
ego-tree = "0.6.2"
image = { version = "0.24.7", optional = true }
whatlang = "0.16.3"
texting_robots = { version = "0.2.2", optional = true }
half = "2.3.1"
srx = { version = "0.1.4", features = ["from_xml"] }
thiserror.workspace = true
anyhow.workspace = true
roaring = "0.10.6"

[features]
default = ["bert", "llama"]
metal = ["rbert?/metal"]
cublas = [
    "rbert?/cuda",
    "rbert?/cudnn"
]
mkl = ["rbert?/mkl"]
openai = ["kalosm-language-model/openai"]
anthropic = ["kalosm-language-model/anthropic"]
remote = ["kalosm-language-model/remote"]
scrape = ["dep:headless_chrome", "dep:image", "dep:dashmap", "dep:texting_robots"]
bert = ["dep:rbert"]
llama = ["dep:kalosm-llama"]

[dev-dependencies]
kalosm = { workspace = true, features = ["language", "surrealdb"], default-features = true }
surrealdb = { version = "2.1.4", features = ["kv-surrealkv"] }

[package.metadata.docs.rs]
# Features to pass to Cargo (default: [])
features = ["remote"]
